const POKEMONARRAY = [
   {
     thumbnail: 'media/bulbasaur.gif',
     id:'001' ,
     name: 'bulbasaur',
     type: ['plant', 'poison'],
   },
   {
     thumbnail: 'media/ivysaur.gif',
     id:'002',
     name: 'ivysaur',
     type: ['plant', 'poison'],
   },
   {
     thumbnail: 'media/venusaur.gif',
     id:'003',
     name: 'venusaur',
     type: ['plant', 'poison'],
   },
   {
     thumbnail: 'media/charmander.gif',
     id:'004',
     name: 'charmander',
     type: ['fire'],
   },
   {
     thumbnail: 'media/charmeleon.gif',
     id:'005',
     name: 'charmeleon',
     type: ['fire'],
   },
   {
     thumbnail: 'media/charizard.gif',
     id:'006',
     name: 'charizard',
     type: ['fire', 'flying'],
   },
   {
     thumbnail: 'media/squirtle.gif',
     id:'007',
     name: 'squirtle',
     type: ['water'],
   },
   {
     thumbnail: 'media/wartortle.gif',
     id:'008',
     name: 'wartortle',
     type: ['water'],
   },
   {
     thumbnail: 'media/blastoise.gif',
     id:'009',
     name: 'blastoise',
     type: ['water'],
   },
   {
     thumbnail: 'media/caterpie.gif',
     id:'010',
     name: 'caterpie',
     type: ['bug'],
   },
   {
     thumbnail: 'media/metapod.gif',
     id:'011',
     name: 'metapod',
     type: ['bug'],
   },
   {
     thumbnail: 'media/butterfree.gif',
     id:'012',
     name: 'butterfree',
     type: ['bug', 'flying'],
   },
   {
     thumbnail: 'media/weedle.gif',
     id:'013',
     name: 'weedle',
     type: ['bug', 'poison'],
   },
   {
     thumbnail: 'media/kakuna.gif',
     id:'014',
     name: 'kakuna',
     type: ['bug', 'poison'],
   },
   {
     thumbnail: 'media/beedrill.gif',
     id:'015',
     name: 'beedrill',
     type: ['bug', 'poison'],
   },
   {
     thumbnail: 'media/pidgey.gif',
     id:'016',
     name: 'pidgey',
     type: ['normal', 'flying'],
   },
   {
    thumbnail: 'media/pidgeotto.gif',
    id:'017',
    name: 'pidgeotto',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/pidgeot.gif',
    id:'018',
    name: 'pidgeot',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/rattata.gif',
    id:'019',
    name: 'rattata',
    type: ['normal'],
  },
  {
    thumbnail: 'media/raticate.gif',
    id:'020',
    name: 'raticate',
    type: ['normal'],
  },
  {
    thumbnail: 'media/spearow.gif',
    id:'021',
    name: 'spearow',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/fearow.gif',
    id:'022',
    name: 'fearow',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/ekans.gif',
    id:'023',
    name: 'ekans',
    type: ['poison'],
  },
  {
    thumbnail: 'media/arbok.gif',
    id:'024',
    name: 'arbok',
    type: ['poison'],
  },
  {
    thumbnail: 'media/pikachu.gif',
    id:'025',
    name: 'pikachu',
    type: ['electric'],
  },
  {
    thumbnail: 'media/raichu.gif',
    id:'026',
    name: 'raichu',
    type: ['electric'],
  },
  {
    thumbnail: 'media/sandshrew.gif',
    id:'027',
    name: 'sandshrew',
    type: ['ground'],
  },
  {
    thumbnail: 'media/sandslash.gif',
    id:'028',
    name: 'sandslash',
    type: ['ground'],
  },
  {
    thumbnail: 'media/nidoran_f.gif',
    id:'029',
    name: 'nidoran',
    type: ['poison'],
  },
  {
    thumbnail: 'media/nidorina.gif',
    id:'030',
    name: 'nidorina',
    type: ['poison'],
  },
  {
    thumbnail: 'media/nidoqueen.gif',
    id:'031',
    name: 'nidoqueen',
    type: ['poison', 'ground'],
  },
  {
    thumbnail: 'media/nidoran_m.gif',
    id:'032',
    name: 'nidoran',
    type: ['poison'],
  },
  {
    thumbnail: 'media/nidorino.gif',
    id:'033',
    name: 'nidorino',
    type: ['poison'],
  },
  {
    thumbnail: 'media/nidoking.gif',
    id:'034',
    name: 'nidoking',
    type: ['poison', 'ground'],
  },
  {
    thumbnail: 'media/clefairy.gif',
    id:'035',
    name: 'clefairy',
    type: ['fairy'],
  },
  {
    thumbnail: 'media/clefable.gif',
    id:'036',
    name: 'clefable',
    type: ['fairy'],
  },
  {
    thumbnail: 'media/vulpix.gif',
    id:'037',
    name: 'vulpix',
    type: ['fire'],
  },
  {
    thumbnail: 'media/ninetales.gif',
    id:'038',
    name: 'ninetales',
    type: ['fire'],
  },
  {
    thumbnail: 'media/jigglypuff.gif',
    id:'039',
    name: 'jigglypuff',
    type: ['normal', 'fairy'],
  },
  {
    thumbnail: 'media/wigglytuff.gif',
    id:'040',
    name: 'wigglytuff',
    type: ['normal', 'fairy'],
  },
  {
    thumbnail: 'media/zubat.gif',
    id:'041',
    name: 'zubat',
    type: ['poison', 'flying'],
  },
  {
    thumbnail: 'media/golbat.gif',
    id:'042',
    name: 'golbat',
    type: ['poison', 'flying'],
  },
  {
    thumbnail: 'media/oddish.gif',
    id:'043',
    name: 'oddish',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/gloom.gif',
    id:'044',
    name: 'gloom',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/vileplume.gif',
    id:'045',
    name: 'vileplume',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/paras.gif',
    id:'046',
    name: 'paras',
    type: ['bug', 'grass'],
  },
  {
    thumbnail: 'media/parasect.gif',
    id:'047',
    name: 'parasect',
    type: ['bug', 'grass'],
  },
  {
    thumbnail: 'media/venonat.gif',
    id:'048',
    name: 'venonat',
    type: ['bug', 'poison'],
  },
  {
    thumbnail: 'media/venomoth.gif',
    id:'049',
    name: 'venomoth',
    type: ['bug', 'poison'],
  },
  {
    thumbnail: 'media/diglett.gif',
    id:'050',
    name: 'diglett',
    type: ['ground'],
  },
  {
    thumbnail: 'media/dugtrio.gif',
    id:'051',
    name: 'dugtrio',
    type: ['ground'],
  },
  {
    thumbnail: 'media/meowth.gif',
    id:'052',
    name: 'meowth',
    type: ['normal'],
  },
  {
    thumbnail: 'media/persian.gif',
    id:'053',
    name: 'persian',
    type: ['normal'],
  },
  {
    thumbnail: 'media/psyduck.gif',
    id:'054',
    name: 'psyduck',
    type: ['water'],
  },
  {
    thumbnail: 'media/golduck.gif',
    id:'055',
    name: 'golduck',
    type: ['water'],
  },
  {
    thumbnail: 'media/mankey.gif',
    id:'056',
    name: 'mankey',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/primeape.gif',
    id:'057',
    name: 'primeape',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/growlithe.gif',
    id:'058',
    name: 'growlithe',
    type: ['fire'],
  },
  {
    thumbnail: 'media/poliwag.gif',
    id:'060',
    name: 'poliwag',
    type: ['water'],
  },
  {
    thumbnail: 'media/poliwhirl.gif',
    id:'061',
    name: 'poliwhirl',
    type: ['water'],
  },
  {
    thumbnail: 'media/poliwrath.gif',
    id:'062',
    name: 'poliwrath',
    type: ['water', 'fighting'],
  },
  {
    thumbnail: 'media/abra.gif',
    id:'063',
    name: 'abra',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/kadabra.gif',
    id:'064',
    name: 'kadabra',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/alakazam.gif',
    id:'065',
    name: 'alakazam',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/machop.gif',
    id:'066',
    name: 'machop',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/machoke.gif',
    id:'067',
    name: 'machoke',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/machamp.gif',
    id:'068',
    name: 'machamp',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/bellsprout.gif',
    id:'069',
    name: 'bellsprout',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/weepinbell.gif',
    id:'070',
    name: 'weepinbell',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/victreebel.gif',
    id:'071',
    name: 'victreebel',
    type: ['grass', 'poison'],
  },
  {
    thumbnail: 'media/tentacool.gif',
    id:'072',
    name: 'tentacool',
    type: ['water', 'poison'],
  },
  {
    thumbnail: 'media/tentacruel.gif',
    id:'073',
    name: 'tentacruel',
    type: ['water', 'poison'],
  },
  {
    thumbnail: 'media/geodude.gif',
    id:'074',
    name: 'geodude',
    type: ['rock', 'ground'],
  },
  {
    thumbnail: 'media/graveler.gif',
    id:'075',
    name: 'graveler',
    type: ['rock', 'ground'],
  },
  {
    thumbnail: 'media/golem.gif',
    id:'076',
    name: 'golem',
    type: ['rock', 'ground'],
  },
  {
    thumbnail: 'media/ponyta.gif',
    id:'077',
    name: 'ponyta',
    type: ['fire'],
  },
  {
    thumbnail: 'media/rapidash.gif',
    id:'078',
    name: 'tentrapidashacool',
    type: ['fire'],
  },
  {
    thumbnail: 'media/slowpoke.gif',
    id:'079',
    name: 'slowpoke',
    type: ['water', 'psychic'],
  },
  {
    thumbnail: 'media/slowbro.gif',
    id:'080',
    name: 'slowbro',
    type: ['water', 'psychic'],
  },
  {
    thumbnail: 'media/magnemite.gif',
    id:'081',
    name: 'magnemite',
    type: ['electric', 'steel'],
  },
  {
    thumbnail: 'media/magneton.gif',
    id:'082',
    name: 'magneton',
    type: ['electric', 'steel'],
  },
  {
    thumbnail: 'media/farfetchd.gif',
    id:'083',
    name: 'farfetchd',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/doduo.gif',
    id:'084',
    name: 'doduo',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/dodrio.gif',
    id:'085',
    name: 'dodrio',
    type: ['normal', 'flying'],
  },
  {
    thumbnail: 'media/seel.gif',
    id:'086',
    name: 'seel',
    type: ['water'],
  },
  {
    thumbnail: 'media/dewgong.gif',
    id:'087',
    name: 'dewgong',
    type: ['water', 'ice'],
  },
  {
    thumbnail: 'media/grimer.gif',
    id:'088',
    name: 'grimer',
    type: ['poison'],
  },
  {
    thumbnail: 'media/muk.gif',
    id:'089',
    name: 'muk',
    type: ['poison'],
  },
  {
    thumbnail: 'media/shellder.gif',
    id:'090',
    name: 'shellder',
    type: ['water'],
  },
  {
    thumbnail: 'media/cloyster.gif',
    id:'091',
    name: 'cloyster',
    type: ['water', 'ice'],
  },
  {
    thumbnail: 'media/gastly.gif',
    id:'092',
    name: 'gastly',
    type: ['ghost', 'poison'],
  },
  {
    thumbnail: 'media/haunter.gif',
    id:'093',
    name: 'haunter',
    type: ['ghost', 'poison'],
  },
  {
    thumbnail: 'media/gengar.gif',
    id:'094',
    name: 'gengar',
    type: ['ghost', 'poison'],
  },
  {
    thumbnail: 'media/onix.gif',
    id:'095',
    name: 'onix',
    type: ['rock', 'ground'],
  },
  {
    thumbnail: 'media/drowzee.gif',
    id:'096',
    name: 'drowzee',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/hypno.gif',
    id:'097',
    name: 'hypno',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/krabby.gif',
    id:'098',
    name: 'krabby',
    type: ['water'],
  },
  {
    thumbnail: 'media/kingler.gif',
    id:'099',
    name: 'kingler',
    type: ['water'],
  },
  {
    thumbnail: 'media/voltorb.gif',
    id:'100',
    name: 'voltorb',
    type: ['electric'],
  },
  {
    thumbnail: 'media/electrode.gif',
    id:'101',
    name: 'electrode',
    type: ['electric'],
  },
  {
    thumbnail: 'media/exeggcute.gif',
    id:'102',
    name: 'exeggcute',
    type: ['grass', 'psychic'],
  },
  {
    thumbnail: 'media/exeggutor.gif',
    id:'103',
    name: 'exeggutor',
    type: ['grass', 'psychic'],
  },
  {
    thumbnail: 'media/cubone.gif',
    id:'104',
    name: 'cubone',
    type: ['ground'],
  },
  {
    thumbnail: 'media/marowak.gif',
    id:'105',
    name: 'marowak',
    type: ['ground'],
  },
  {
    thumbnail: 'media/hitmonlee.gif',
    id:'106',
    name: 'hitmonlee',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/hitmonchan.gif',
    id:'107',
    name: 'hitmonchan',
    type: ['fighting'],
  },
  {
    thumbnail: 'media/lickitung.gif',
    id:'108',
    name: 'lickitung',
    type: ['normal'],
  },
  {
    thumbnail: 'media/koffing.gif',
    id:'109',
    name: 'koffing',
    type: ['poison'],
  },
  {
    thumbnail: 'media/weezing.gif',
    id:'110',
    name: 'weezing',
    type: ['poison'],
  },
  {
    thumbnail: 'media/rhyhorn.gif',
    id:'111',
    name: 'rhyhorn',
    type: ['ground', 'rock'],
  },
  {
    thumbnail: 'media/rhydon.gif',
    id:'112',
    name: 'rhydon',
    type: ['ground', 'rock'],
  },
  {
    thumbnail: 'media/chansey.gif',
    id:'113',
    name: 'chansey',
    type: ['normal'],
  },
  {
    thumbnail: 'media/tangela.gif',
    id:'114',
    name: 'tangela',
    type: ['grass'],
  },
  {
    thumbnail: 'media/kangaskhan.gif',
    id:'115',
    name: 'kangaskhan',
    type: ['normal'],
  },
  {
    thumbnail: 'media/horsea.gif',
    id:'116',
    name: 'horsea',
    type: ['water'],
  },
  {
    thumbnail: 'media/seadra.gif',
    id:'117',
    name: 'seadra',
    type: ['water'],
  },
  {
    thumbnail: 'media/goldeen.gif',
    id:'118',
    name: 'goldeen',
    type: ['water'],
  },
  {
    thumbnail: 'media/seaking.gif',
    id:'119',
    name: 'seaking',
    type: ['water'],
  },
  {
    thumbnail: 'media/staryu.gif',
    id:'120',
    name: 'staryu',
    type: ['water'],
  },
  {
    thumbnail: 'media/starmie.gif',
    id:'121',
    name: 'starmie',
    type: ['water', 'psychic'],
  },
  {
    thumbnail: 'media/mr.mime.gif',
    id:'122',
    name: 'mr.mime',
    type: ['psychic', 'fairy'],
  },
  {
    thumbnail: 'media/scyther.gif',
    id:'123',
    name: 'scyther',
    type: ['bug', 'flying'],
  },
  {
    thumbnail: 'media/jynx.gif',
    id:'124',
    name: 'jynx',
    type: ['ice', 'psychic'],
  },
  {
    thumbnail: 'media/electabuzz.gif',
    id:'125',
    name: 'electabuzz',
    type: ['electric'],
  },
  {
    thumbnail: 'media/magmar.gif',
    id:'126',
    name: 'magmar',
    type: ['fire'],
  },
  {
    thumbnail: 'media/pinsir.gif',
    id:'127',
    name: 'pinsir',
    type: ['bug'],
  },
  {
    thumbnail: 'media/tauros.gif',
    id:'128',
    name: 'tauros',
    type: ['normal'],
  },
  {
    thumbnail: 'media/magikarp.gif',
    id:'129',
    name: 'magikarp',
    type: ['water'],
  },
  {
    thumbnail: 'media/gyarados.gif',
    id:'130',
    name: 'gyarados',
    type: ['water', 'flying'],
  },
  {
    thumbnail: 'media/lapras.gif',
    id:'131',
    name: 'lapras',
    type: ['water', 'ice'],
  },
  {
    thumbnail: 'media/ditto.gif',
    id:'132',
    name: 'ditto',
    type: ['normal'],
  },
  {
    thumbnail: 'media/eevee.gif',
    id:'133',
    name: 'eevee',
    type: ['normal'],
  },
  {
    thumbnail: 'media/vaporeon.gif',
    id:'134',
    name: 'vaporeon',
    type: ['water'],
  },
  {
    thumbnail: 'media/jolteon.gif',
    id:'135',
    name: 'jolteon',
    type: ['electric'],
  },
  {
    thumbnail: 'media/flareon.gif',
    id:'136',
    name: 'flareon',
    type: ['fire'],
  },
  {
    thumbnail: 'media/porygon.gif',
    id:'137',
    name: 'porygon',
    type: ['normal'],
  },
  {
    thumbnail: 'media/omanyte.gif',
    id:'138',
    name: 'omanyte',
    type: ['rock', 'water'],
  },
  {
    thumbnail: 'media/omastar.gif',
    id:'139',
    name: 'omastar',
    type: ['rock', 'water'],
  },
  {
    thumbnail: 'media/kabuto.gif',
    id:'140',
    name: 'kabuto',
    type: ['rock', 'water'],
  },
  {
    thumbnail: 'media/kabutops.gif',
    id:'141',
    name: 'kabutops',
    type: ['rock', 'water'],
  },
  {
    thumbnail: 'media/aerodactyl.gif',
    id:'142',
    name: 'aerodactyl',
    type: ['rock', 'flying'],
  },
  {
    thumbnail: 'media/snorlax.gif',
    id:'143',
    name: 'snorlax',
    type: ['normal'],
  },
  {
    thumbnail: 'media/articuno.gif',
    id:'144',
    name: 'articuno',
    type: ['ice', 'flying'],
  },
  {
    thumbnail: 'media/zapdos.gif',
    id:'145',
    name: 'zapdos',
    type: ['electric', 'flying'],
  },
  {
    thumbnail: 'media/moltres.gif',
    id:'146',
    name: 'moltres',
    type: ['fire', 'flying'],
  },
  {
    thumbnail: 'media/dratini.gif',
    id:'147',
    name: 'dratini',
    type: ['dragon'],
  },
  {
    thumbnail: 'media/dragonair.gif',
    id:'148',
    name: 'dragonair',
    type: ['dragon'],
  },
  {
    thumbnail: 'media/dragonite.gif',
    id:'149',
    name: 'dragonite',
    type: ['dragon', 'flying'],
  },
  {
    thumbnail: 'media/mewtwo.gif',
    id:'150',
    name: 'mewtwo',
    type: ['psychic'],
  },
  {
    thumbnail: 'media/mew.gif',
    id:'151',
    name: 'mew',
    type: ['psychic'],
  },
 ];

 export { POKEMONARRAY };